# Generated by Django 3.0.7 on 2020-07-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_serie', models.CharField(max_length=15)),
                ('Type_E', models.CharField(max_length=15)),
                ('TypeEtat', models.CharField(default='NonAttribue', max_length=15)),
                ('dateE_Ajouter', models.DateField(auto_now=True)),
            ],
        ),
    ]
