# Generated by Django 3.0.7 on 2020-07-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='equipement',
            name='Type_E',
            field=models.CharField(max_length=25),
        ),
    ]
