# Generated by Django 3.0.7 on 2020-07-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_auto_20200715_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='Type_E',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipement.TypeE'),
        ),
    ]
