# Generated by Django 3.0.7 on 2020-09-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0005_equipement_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEtat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameT', models.CharField(max_length=25)),
            ],
        ),
    ]
