# Generated by Django 3.0.7 on 2020-09-15 06:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0009_delete_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nom Du Categorie')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='N_serie',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='TypeEtat',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='Type_E',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='dateE_Ajouter',
        ),
        migrations.AddField(
            model_name='equipement',
            name='date_ajoute',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipement',
            name='etat_equipement',
            field=models.CharField(choices=[('0', 'Non attribut'), ('1', 'Attribué')], default='0', max_length=15, verbose_name='etat'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='nom',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipement',
            name='num_serie',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TypeE',
        ),
        migrations.DeleteModel(
            name='TypeEtat',
        ),
        migrations.AddField(
            model_name='equipement',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoryE', to='equipement.Category'),
            preserve_default=False,
        ),
    ]
