# Generated by Django 3.0.7 on 2020-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200915_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/avatar1.jpg', null=True, upload_to=''),
        ),
    ]
