# Generated by Django 3.0.7 on 2020-09-10 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipement', '0004_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=20)),
                ('lieu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('mac', macaddress.fields.MACAddressField(integer=True, verbose_name='Adesse Mac')),
                ('date_installe', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomD', to='installation.Direction')),
                ('equipement_installe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation_equipement', to='equipement.Equipement')),
            ],
        ),
    ]
