# Generated by Django 3.0.7 on 2020-09-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_auto_20200913_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='nameD',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='installation',
            old_name='direction',
            new_name='Nom_direction',
        ),
        migrations.AddField(
            model_name='installation',
            name='service',
            field=models.CharField(choices=[('En service', 'En service'), ('En panne', 'En panne'), ('A remplace', 'A remplace')], default='En service', max_length=15),
        ),
    ]
