# Generated by Django 3.0.7 on 2020-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0004_installation_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='service',
            field=models.CharField(choices=[('En service', 'En service'), ('En panne', 'En panne')], default='En service', max_length=15),
        ),
    ]
